---
- name: Install Python using pyenv
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.pyenv/bin"
  block:
    - name: Create download directory
      file:
        path: "{{ python3_tmpdir }}"
        state: directory
        mode: 0700
      changed_when: false  # tmpdir role removes directory automatically

    - name: Install pyenv
      block:
        - name: Download pyenv installer
          get_url:
            url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
            dest: "{{ python3_tmpdir }}"
          changed_when: false  # temporary directory is removed when play ends

        - name: Run pyenv installer
          command: "bash pyenv-installer"
          args:
            chdir: "{{ python3_tmpdir }}"
            creates: "{{ ansible_user_dir }}/.pyenv"

        - name: Update login file
          blockinfile:
            path: "{{ python3_bashrc }}"
            create: true
            block: |
              export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
              eval "$(pyenv init -)"
              eval "$(pyenv virtualenv-init -)"
            mode: 0644

        - name: Update pyenv
          command: pyenv update

    - name: Install Python
      block:
        - name: Install Python
          command: "pyenv install {{ python3_pyenv }}"
          args:
            creates: "{{ ansible_user_dir }}/.pyenv/versions/{{ python3_pyenv }}"

        - name: Execute pyenv rehash
          command: "pyenv rehash"

        - name: Define python3 command
          set_fact:  # can't rely on changes to $PATH yet
            python3_command: "{{ ansible_user_dir }}/.pyenv/shims/{{ python3_command }}"
